import type { ZodType } from 'zod';
import type { Scope } from './common';
import { listQuerySchema } from './common';
import {
  apiTokenCreateSchema,
  approvalCreateSchema,
  approvalDecideSchema,
  bulkCompleteSchema,
  commentCreateSchema,
  companyCreateSchema,
  companyUpdateSchema,
  contactCreateSchema,
  contactUpdateSchema,
  customFieldCreateSchema,
  customFieldReorderSchema,
  customFieldUpdateSchema,
  dealCreateSchema,
  dealMoveSchema,
  dealUpdateSchema,
  emailDraftSchema,
  emailTemplateUpsertSchema,
  importCreateSchema,
  invoiceCreateSchema,
  invoiceSendSchema,
  invoiceUpdateSchema,
  loginSchema,
  memberInviteSchema,
  memberUpdateSchema,
  mergeSchema,
  noteCreateSchema,
  paymentCreateSchema,
  pipelineCreateSchema,
  reportQuerySchema,
  secretUpsertSchema,
  switchTenantSchema,
  taskCreateSchema,
  taskUpdateSchema,
} from './records';
import {
  draftSaveSchema,
  manualRunSchema,
  testRunSchema,
  workflowCreateSchema,
  workflowUpdateSchema,
} from './workflow';

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export interface RouteSpec {
  method: HttpMethod;
  path: string;
  summary: string;
  tag: string;
  scope?: Scope;
  auth?: 'public' | 'user' | 'any';
  body?: ZodType;
  query?: ZodType;
  response?: string;
  idempotent?: boolean;
  ifMatch?: boolean;
}

const r = (spec: RouteSpec): RouteSpec => spec;

export const API_ROUTES: RouteSpec[] = [
  r({ method: 'GET', path: '/health', summary: 'Liveness and dependency status', tag: 'system', auth: 'public' }),
  r({ method: 'GET', path: '/metrics', summary: 'Prometheus metrics', tag: 'system', auth: 'public' }),
  r({ method: 'GET', path: '/openapi.json', summary: 'This OpenAPI document', tag: 'system', auth: 'public' }),
  r({
    method: 'GET',
    path: '/v1/app-config',
    summary: 'Public SPA configuration (optional integrations such as the operator panel)',
    tag: 'system',
    auth: 'public',
    response: 'AppConfigDto',
  }),
  r({
    method: 'GET',
    path: '/docs',
    summary: 'API reference page (self-contained, no CDN)',
    tag: 'system',
    auth: 'public',
  }),
  r({
    method: 'POST',
    path: '/v1/auth/login',
    summary: 'Log in, sets the refresh cookie',
    tag: 'auth',
    auth: 'public',
    body: loginSchema,
    response: 'LoginResponse',
  }),
  r({
    method: 'POST',
    path: '/v1/auth/refresh',
    summary: 'New access token from the refresh cookie',
    tag: 'auth',
    auth: 'public',
    response: 'LoginResponse',
  }),
  r({ method: 'POST', path: '/v1/auth/logout', summary: 'Revoke the refresh cookie', tag: 'auth', auth: 'public' }),
  r({
    method: 'POST',
    path: '/v1/auth/switch-tenant',
    summary: 'Switch workspace',
    tag: 'auth',
    auth: 'user',
    body: switchTenantSchema,
    response: 'LoginResponse',
  }),
  r({
    method: 'GET',
    path: '/v1/me',
    summary: 'Current user, workspace, role and scopes',
    tag: 'auth',
    auth: 'any',
    response: 'MeDto',
  }),
  r({
    method: 'POST',
    path: '/v1/realtime/ticket',
    summary: 'One-time ticket for the realtime server (503 when it is not configured)',
    tag: 'realtime',
    auth: 'user',
  }),
  r({
    method: 'GET',
    path: '/v1/notifications/stream',
    summary: 'Server-sent events with notifications (fallback for realtime)',
    tag: 'notifications',
    auth: 'user',
  }),
  r({
    method: 'GET',
    path: '/v1/members',
    summary: 'Workspace members',
    tag: 'settings',
    scope: 'records:read',
    response: 'MemberDto[]',
  }),
  r({
    method: 'POST',
    path: '/v1/members',
    summary: 'Add a member',
    tag: 'settings',
    scope: 'admin',
    body: memberInviteSchema,
  }),
  r({
    method: 'PATCH',
    path: '/v1/members/:userId',
    summary: 'Change role',
    tag: 'settings',
    scope: 'admin',
    body: memberUpdateSchema,
  }),
  r({ method: 'DELETE', path: '/v1/members/:userId', summary: 'Remove member', tag: 'settings', scope: 'admin' }),
  r({
    method: 'PATCH',
    path: '/v1/settings',
    summary: 'Update workspace settings',
    tag: 'settings',
    scope: 'admin',
    response: 'TenantSettings',
  }),

  r({
    method: 'GET',
    path: '/v1/companies',
    summary: 'List companies (cursor, filter chips, sort incl. custom.<key>)',
    tag: 'companies',
    scope: 'records:read',
    query: listQuerySchema,
    response: 'Page<CompanyDto>',
  }),
  r({
    method: 'POST',
    path: '/v1/companies',
    summary: 'Create company',
    tag: 'companies',
    scope: 'records:write',
    body: companyCreateSchema,
    response: 'CompanyDto',
  }),
  r({
    method: 'GET',
    path: '/v1/companies/duplicates',
    summary: 'Duplicate candidates',
    tag: 'companies',
    scope: 'records:read',
  }),
  r({
    method: 'POST',
    path: '/v1/companies/merge',
    summary: 'Merge duplicates into a target',
    tag: 'companies',
    scope: 'records:write',
    body: mergeSchema,
    response: 'CompanyDto',
  }),
  r({
    method: 'POST',
    path: '/v1/companies/import',
    summary: 'Import CSV (background job)',
    tag: 'companies',
    scope: 'records:write',
    body: importCreateSchema,
    response: 'ImportJobDto',
  }),
  r({
    method: 'GET',
    path: '/v1/companies/:id',
    summary: 'Company with stats (ETag)',
    tag: 'companies',
    scope: 'records:read',
    response: 'CompanyDto',
  }),
  r({
    method: 'PATCH',
    path: '/v1/companies/:id',
    summary: 'Update company (If-Match)',
    tag: 'companies',
    scope: 'records:write',
    body: companyUpdateSchema,
    ifMatch: true,
    response: 'CompanyDto',
  }),
  r({ method: 'DELETE', path: '/v1/companies/:id', summary: 'Soft delete', tag: 'companies', scope: 'records:write' }),
  r({
    method: 'GET',
    path: '/v1/companies/:id/timeline',
    summary: 'Activity timeline',
    tag: 'companies',
    scope: 'records:read',
    response: 'Page<ActivityDto>',
  }),

  r({
    method: 'GET',
    path: '/v1/contacts',
    summary: 'List contacts',
    tag: 'contacts',
    scope: 'records:read',
    query: listQuerySchema,
    response: 'Page<ContactDto>',
  }),
  r({
    method: 'POST',
    path: '/v1/contacts',
    summary: 'Create contact',
    tag: 'contacts',
    scope: 'records:write',
    body: contactCreateSchema,
    response: 'ContactDto',
  }),
  r({
    method: 'GET',
    path: '/v1/contacts/duplicates',
    summary: 'Duplicate candidates',
    tag: 'contacts',
    scope: 'records:read',
  }),
  r({
    method: 'POST',
    path: '/v1/contacts/merge',
    summary: 'Merge duplicates',
    tag: 'contacts',
    scope: 'records:write',
    body: mergeSchema,
    response: 'ContactDto',
  }),
  r({
    method: 'POST',
    path: '/v1/contacts/import',
    summary: 'Import CSV (background job)',
    tag: 'contacts',
    scope: 'records:write',
    body: importCreateSchema,
    response: 'ImportJobDto',
  }),
  r({
    method: 'GET',
    path: '/v1/contacts/:id',
    summary: 'Contact (ETag)',
    tag: 'contacts',
    scope: 'records:read',
    response: 'ContactDto',
  }),
  r({
    method: 'PATCH',
    path: '/v1/contacts/:id',
    summary: 'Update contact (If-Match)',
    tag: 'contacts',
    scope: 'records:write',
    body: contactUpdateSchema,
    ifMatch: true,
    response: 'ContactDto',
  }),
  r({ method: 'DELETE', path: '/v1/contacts/:id', summary: 'Soft delete', tag: 'contacts', scope: 'records:write' }),
  r({
    method: 'GET',
    path: '/v1/contacts/:id/timeline',
    summary: 'Activity timeline',
    tag: 'contacts',
    scope: 'records:read',
    response: 'Page<ActivityDto>',
  }),
  r({
    method: 'GET',
    path: '/v1/imports',
    summary: 'Recent imports',
    tag: 'imports',
    scope: 'records:read',
    response: 'ImportJobDto[]',
  }),
  r({
    method: 'GET',
    path: '/v1/imports/:id',
    summary: 'Import progress and error report',
    tag: 'imports',
    scope: 'records:read',
    response: 'ImportJobDto',
  }),

  r({
    method: 'GET',
    path: '/v1/pipelines',
    summary: 'Pipelines with stages',
    tag: 'deals',
    scope: 'records:read',
    response: 'PipelineDto[]',
  }),
  r({
    method: 'POST',
    path: '/v1/pipelines',
    summary: 'Create pipeline',
    tag: 'deals',
    scope: 'admin',
    body: pipelineCreateSchema,
    response: 'PipelineDto',
  }),
  r({
    method: 'PUT',
    path: '/v1/pipelines/:id',
    summary: 'Replace pipeline stages',
    tag: 'deals',
    scope: 'admin',
    body: pipelineCreateSchema,
    response: 'PipelineDto',
  }),
  r({
    method: 'GET',
    path: '/v1/deals',
    summary: 'List deals',
    tag: 'deals',
    scope: 'records:read',
    query: listQuerySchema,
    response: 'Page<DealDto>',
  }),
  r({
    method: 'GET',
    path: '/v1/deals/board',
    summary: 'Kanban board for a pipeline',
    tag: 'deals',
    scope: 'records:read',
  }),
  r({
    method: 'GET',
    path: '/v1/deals/forecast',
    summary: 'Weighted forecast',
    tag: 'deals',
    scope: 'records:read',
    response: 'ForecastDto',
  }),
  r({
    method: 'POST',
    path: '/v1/deals',
    summary: 'Create deal',
    tag: 'deals',
    scope: 'records:write',
    body: dealCreateSchema,
    response: 'DealDto',
  }),
  r({
    method: 'GET',
    path: '/v1/deals/:id',
    summary: 'Deal (ETag)',
    tag: 'deals',
    scope: 'records:read',
    response: 'DealDto',
  }),
  r({
    method: 'PATCH',
    path: '/v1/deals/:id',
    summary: 'Update deal (If-Match)',
    tag: 'deals',
    scope: 'records:write',
    body: dealUpdateSchema,
    ifMatch: true,
    idempotent: true,
    response: 'DealDto',
  }),
  r({
    method: 'PATCH',
    path: '/v1/deals/:id/move',
    summary: 'Move between stages / reorder (fractional index)',
    tag: 'deals',
    scope: 'records:write',
    body: dealMoveSchema,
    ifMatch: true,
    idempotent: true,
    response: 'DealDto',
  }),
  r({ method: 'DELETE', path: '/v1/deals/:id', summary: 'Soft delete', tag: 'deals', scope: 'records:write' }),
  r({
    method: 'GET',
    path: '/v1/deals/:id/timeline',
    summary: 'Activity timeline',
    tag: 'deals',
    scope: 'records:read',
    response: 'Page<ActivityDto>',
  }),

  r({
    method: 'GET',
    path: '/v1/invoices',
    summary: 'List invoices',
    tag: 'invoices',
    scope: 'records:read',
    query: listQuerySchema,
    response: 'Page<InvoiceDto>',
  }),
  r({
    method: 'POST',
    path: '/v1/invoices',
    summary: 'Create invoice (Idempotency-Key)',
    tag: 'invoices',
    scope: 'records:write',
    body: invoiceCreateSchema,
    idempotent: true,
    response: 'InvoiceDto',
  }),
  r({
    method: 'GET',
    path: '/v1/invoices/:id',
    summary: 'Invoice with lines and payments (ETag)',
    tag: 'invoices',
    scope: 'records:read',
    response: 'InvoiceDto',
  }),
  r({
    method: 'PATCH',
    path: '/v1/invoices/:id',
    summary: 'Update invoice (If-Match)',
    tag: 'invoices',
    scope: 'records:write',
    body: invoiceUpdateSchema,
    ifMatch: true,
    response: 'InvoiceDto',
  }),
  r({ method: 'DELETE', path: '/v1/invoices/:id', summary: 'Delete a draft', tag: 'invoices', scope: 'records:write' }),
  r({
    method: 'POST',
    path: '/v1/invoices/:id/send',
    summary: 'Email with PDF (Idempotency-Key)',
    tag: 'invoices',
    scope: 'invoices:send',
    body: invoiceSendSchema,
    idempotent: true,
    response: 'InvoiceDto',
  }),
  r({
    method: 'POST',
    path: '/v1/invoices/:id/payments',
    summary: 'Record payment (Idempotency-Key)',
    tag: 'invoices',
    scope: 'records:write',
    body: paymentCreateSchema,
    idempotent: true,
    response: 'InvoiceDto',
  }),
  r({
    method: 'POST',
    path: '/v1/invoices/:id/void',
    summary: 'Void (dryRun supported, Idempotency-Key)',
    tag: 'invoices',
    scope: 'invoices:void',
    idempotent: true,
    response: 'InvoiceDto',
  }),
  r({
    method: 'GET',
    path: '/v1/invoices/:id/pdf',
    summary: 'PDF rendered by the Chromium worker',
    tag: 'invoices',
    scope: 'records:read',
  }),
  r({
    method: 'GET',
    path: '/v1/invoices/:id/preview',
    summary: 'HTML preview of the PDF template',
    tag: 'invoices',
    scope: 'records:read',
  }),
  r({
    method: 'GET',
    path: '/v1/invoices/:id/timeline',
    summary: 'Activity timeline',
    tag: 'invoices',
    scope: 'records:read',
    response: 'Page<ActivityDto>',
  }),
  r({
    method: 'GET',
    path: '/p/invoices/:token',
    summary: 'Public invoice page data',
    tag: 'public',
    auth: 'public',
    response: 'PublicInvoiceDto',
  }),
  r({ method: 'GET', path: '/p/invoices/:token/pdf', summary: 'Public invoice PDF', tag: 'public', auth: 'public' }),
  r({
    method: 'POST',
    path: '/p/invoices/:token/pay',
    summary: 'Demo: mark as paid',
    tag: 'public',
    auth: 'public',
    response: 'PublicInvoiceDto',
  }),

  r({
    method: 'GET',
    path: '/v1/tasks',
    summary: 'List tasks',
    tag: 'tasks',
    scope: 'records:read',
    query: listQuerySchema,
    response: 'Page<TaskDto>',
  }),
  r({
    method: 'GET',
    path: '/v1/tasks/my',
    summary: 'My open tasks',
    tag: 'tasks',
    scope: 'records:read',
    response: 'Page<TaskDto>',
  }),
  r({
    method: 'POST',
    path: '/v1/tasks',
    summary: 'Create task (dryRun supported, Idempotency-Key)',
    tag: 'tasks',
    scope: 'records:write',
    body: taskCreateSchema,
    idempotent: true,
    response: 'TaskDto',
  }),
  r({
    method: 'POST',
    path: '/v1/tasks/bulk-complete',
    summary: 'Complete several tasks',
    tag: 'tasks',
    scope: 'records:write',
    body: bulkCompleteSchema,
  }),
  r({
    method: 'GET',
    path: '/v1/tasks/:id',
    summary: 'Task',
    tag: 'tasks',
    scope: 'records:read',
    response: 'TaskDto',
  }),
  r({
    method: 'PATCH',
    path: '/v1/tasks/:id',
    summary: 'Update task',
    tag: 'tasks',
    scope: 'records:write',
    body: taskUpdateSchema,
    response: 'TaskDto',
  }),
  r({ method: 'DELETE', path: '/v1/tasks/:id', summary: 'Delete task', tag: 'tasks', scope: 'records:write' }),

  r({
    method: 'GET',
    path: '/v1/records/:type/:id/timeline',
    summary: 'Timeline of any record',
    tag: 'activity',
    scope: 'records:read',
    response: 'Page<ActivityDto>',
  }),
  r({
    method: 'GET',
    path: '/v1/records/:type/:id/tasks',
    summary: 'Tasks related to a record',
    tag: 'activity',
    scope: 'records:read',
    response: 'TaskDto[]',
  }),
  r({
    method: 'GET',
    path: '/v1/records/:type/:id/emails',
    summary: 'Emails related to a record',
    tag: 'activity',
    scope: 'records:read',
    response: 'EmailMessageDto[]',
  }),
  r({
    method: 'GET',
    path: '/v1/comments',
    summary: 'Comments of a record',
    tag: 'activity',
    scope: 'records:read',
    response: 'CommentDto[]',
  }),
  r({
    method: 'POST',
    path: '/v1/comments',
    summary: 'Comment with @mentions (@[Name](userId))',
    tag: 'activity',
    scope: 'records:write',
    body: commentCreateSchema,
    response: 'CommentDto',
  }),
  r({
    method: 'POST',
    path: '/v1/notes',
    summary: 'Log a note, call, email or meeting (dryRun supported)',
    tag: 'activity',
    scope: 'records:write',
    body: noteCreateSchema,
    idempotent: true,
    response: 'ActivityDto',
  }),
  r({ method: 'GET', path: '/v1/notifications', summary: 'My notifications', tag: 'notifications', auth: 'user' }),
  r({
    method: 'POST',
    path: '/v1/notifications/read',
    summary: 'Mark read ({ids} or {all:true})',
    tag: 'notifications',
    auth: 'user',
  }),
  r({
    method: 'GET',
    path: '/v1/audit',
    summary: 'Audit log with actorType',
    tag: 'activity',
    scope: 'admin',
    response: 'Page<AuditLogDto>',
  }),

  r({
    method: 'GET',
    path: '/v1/custom-fields',
    summary: 'Custom field definitions',
    tag: 'custom-fields',
    scope: 'records:read',
    response: 'CustomFieldDefDto[]',
  }),
  r({
    method: 'POST',
    path: '/v1/custom-fields',
    summary: 'Create definition (indexed → expression index)',
    tag: 'custom-fields',
    scope: 'admin',
    body: customFieldCreateSchema,
    response: 'CustomFieldDefDto',
  }),
  r({
    method: 'POST',
    path: '/v1/custom-fields/reorder',
    summary: 'Reorder',
    tag: 'custom-fields',
    scope: 'admin',
    body: customFieldReorderSchema,
  }),
  r({
    method: 'PATCH',
    path: '/v1/custom-fields/:id',
    summary: 'Update definition',
    tag: 'custom-fields',
    scope: 'admin',
    body: customFieldUpdateSchema,
    response: 'CustomFieldDefDto',
  }),
  r({
    method: 'DELETE',
    path: '/v1/custom-fields/:id',
    summary: 'Delete definition',
    tag: 'custom-fields',
    scope: 'admin',
  }),

  r({
    method: 'GET',
    path: '/v1/search',
    summary: 'Global search (FTS + trigram) grouped by type',
    tag: 'search',
    scope: 'records:read',
    response: 'SearchResult',
  }),
  r({
    method: 'GET',
    path: '/v1/reports/pipeline',
    summary: 'Funnel by stage',
    tag: 'reports',
    scope: 'reports:read',
    query: reportQuerySchema,
    response: 'PipelineReportDto',
  }),
  r({
    method: 'GET',
    path: '/v1/reports/revenue',
    summary: 'Won deals vs invoiced vs paid by month',
    tag: 'reports',
    scope: 'reports:read',
    query: reportQuerySchema,
    response: 'RevenueReportDto',
  }),
  r({
    method: 'GET',
    path: '/v1/reports/ar-aging',
    summary: 'Receivables aging',
    tag: 'reports',
    scope: 'reports:read',
    response: 'ArAgingReportDto',
  }),
  r({
    method: 'GET',
    path: '/v1/reports/activity',
    summary: 'Team activity',
    tag: 'reports',
    scope: 'reports:read',
    query: reportQuerySchema,
    response: 'ActivityReportDto',
  }),

  r({
    method: 'GET',
    path: '/v1/api-tokens',
    summary: 'API tokens',
    tag: 'settings',
    scope: 'admin',
    response: 'ApiTokenDto[]',
  }),
  r({
    method: 'POST',
    path: '/v1/api-tokens',
    summary: 'Create token (value shown once)',
    tag: 'settings',
    auth: 'user',
    body: apiTokenCreateSchema,
  }),
  r({ method: 'DELETE', path: '/v1/api-tokens/:id', summary: 'Revoke token', tag: 'settings', scope: 'admin' }),
  r({
    method: 'GET',
    path: '/v1/secrets',
    summary: 'Secret names (values are never returned)',
    tag: 'settings',
    scope: 'admin',
    response: 'SecretDto[]',
  }),
  r({
    method: 'PUT',
    path: '/v1/secrets/:name',
    summary: 'Create or replace secret',
    tag: 'settings',
    scope: 'admin',
    body: secretUpsertSchema.pick({ value: true }),
  }),
  r({ method: 'DELETE', path: '/v1/secrets/:name', summary: 'Delete secret', tag: 'settings', scope: 'admin' }),
  r({
    method: 'GET',
    path: '/v1/email-templates',
    summary: 'Email templates',
    tag: 'settings',
    scope: 'records:read',
    response: 'EmailTemplateDto[]',
  }),
  r({
    method: 'PUT',
    path: '/v1/email-templates/:key',
    summary: 'Create or update template',
    tag: 'settings',
    scope: 'admin',
    body: emailTemplateUpsertSchema.omit({ key: true }),
  }),
  r({
    method: 'DELETE',
    path: '/v1/email-templates/:key',
    summary: 'Delete template',
    tag: 'settings',
    scope: 'admin',
  }),
  r({
    method: 'POST',
    path: '/v1/email-templates/preview',
    summary: 'Render a template against a record',
    tag: 'settings',
    scope: 'records:read',
  }),
  r({
    method: 'POST',
    path: '/v1/emails/drafts',
    summary: 'Create an email draft (not sent)',
    tag: 'emails',
    scope: 'records:write',
    body: emailDraftSchema,
    idempotent: true,
    response: 'EmailMessageDto',
  }),
  r({
    method: 'GET',
    path: '/v1/emails/:id',
    summary: 'Email',
    tag: 'emails',
    scope: 'records:read',
    response: 'EmailMessageDto',
  }),
  r({
    method: 'POST',
    path: '/v1/emails/:id/send',
    summary: 'Send a draft (Idempotency-Key)',
    tag: 'emails',
    scope: 'email:send',
    idempotent: true,
    response: 'EmailMessageDto',
  }),

  r({
    method: 'GET',
    path: '/v1/approvals',
    summary: 'Approvals (?status=pending&mine=1)',
    tag: 'approvals',
    scope: 'approvals:read',
    response: 'ApprovalDto[]',
  }),
  r({
    method: 'GET',
    path: '/v1/approvals/count',
    summary: 'Pending approvals for me',
    tag: 'approvals',
    scope: 'approvals:read',
  }),
  r({
    method: 'POST',
    path: '/v1/approvals',
    summary: 'Request approval from an external source (decision → callbackUrl webhook)',
    tag: 'approvals',
    scope: 'approvals:create',
    body: approvalCreateSchema,
    response: 'ApprovalDto',
  }),
  r({
    method: 'GET',
    path: '/v1/approvals/:id',
    summary: 'Approval',
    tag: 'approvals',
    scope: 'approvals:read',
    response: 'ApprovalDto',
  }),
  r({
    method: 'POST',
    path: '/v1/approvals/:id/decide',
    summary: 'Approve or reject',
    tag: 'approvals',
    scope: 'approvals:decide',
    body: approvalDecideSchema,
    response: 'ApprovalDto',
  }),

  r({
    method: 'GET',
    path: '/v1/workflows',
    summary: 'Workflows with run stats',
    tag: 'workflows',
    scope: 'workflows:read',
    response: 'WorkflowDto[]',
  }),
  r({
    method: 'POST',
    path: '/v1/workflows',
    summary: 'Create (blank or from template)',
    tag: 'workflows',
    scope: 'workflows:write',
    body: workflowCreateSchema,
    response: 'WorkflowDetailDto',
  }),
  r({
    method: 'GET',
    path: '/v1/workflows/templates',
    summary: 'Template gallery',
    tag: 'workflows',
    scope: 'workflows:read',
    response: 'WorkflowTemplateDto[]',
  }),
  r({
    method: 'POST',
    path: '/v1/workflows/validate',
    summary: 'Validate a definition',
    tag: 'workflows',
    scope: 'workflows:read',
  }),
  r({
    method: 'GET',
    path: '/v1/workflows/:id',
    summary: 'Workflow with draft, active version and versions',
    tag: 'workflows',
    scope: 'workflows:read',
    response: 'WorkflowDetailDto',
  }),
  r({
    method: 'PATCH',
    path: '/v1/workflows/:id',
    summary: 'Rename, activate, pause, archive',
    tag: 'workflows',
    scope: 'workflows:write',
    body: workflowUpdateSchema,
    response: 'WorkflowDetailDto',
  }),
  r({ method: 'DELETE', path: '/v1/workflows/:id', summary: 'Archive', tag: 'workflows', scope: 'workflows:write' }),
  r({
    method: 'PUT',
    path: '/v1/workflows/:id/draft',
    summary: 'Autosave draft, returns validation issues',
    tag: 'workflows',
    scope: 'workflows:write',
    body: draftSaveSchema,
  }),
  r({
    method: 'GET',
    path: '/v1/workflows/:id/diff',
    summary: 'Draft vs active version',
    tag: 'workflows',
    scope: 'workflows:read',
  }),
  r({
    method: 'POST',
    path: '/v1/workflows/:id/publish',
    summary: 'Publish draft as a new immutable version',
    tag: 'workflows',
    scope: 'workflows:write',
    response: 'WorkflowDetailDto',
  }),
  r({
    method: 'GET',
    path: '/v1/workflows/:id/versions/:version',
    summary: 'Published version',
    tag: 'workflows',
    scope: 'workflows:read',
  }),
  r({
    method: 'POST',
    path: '/v1/workflows/:id/runs',
    summary: 'Start a manual run',
    tag: 'workflows',
    scope: 'workflows:write',
    body: manualRunSchema,
    response: 'RunDto',
  }),
  r({
    method: 'POST',
    path: '/v1/workflows/:id/test-runs',
    summary: 'Test run (dry-run effects)',
    tag: 'workflows',
    scope: 'workflows:write',
    body: testRunSchema,
    response: 'RunDto',
  }),
  r({
    method: 'GET',
    path: '/v1/workflow-runs',
    summary: 'Runs (?workflowId&status&includeTests)',
    tag: 'workflows',
    scope: 'workflows:read',
    response: 'Page<RunDto>',
  }),
  r({
    method: 'GET',
    path: '/v1/workflow-runs/:id',
    summary: 'Run with steps for replay',
    tag: 'workflows',
    scope: 'workflows:read',
    response: 'RunDetailDto',
  }),
  r({
    method: 'POST',
    path: '/v1/workflow-runs/:id/cancel',
    summary: 'Cancel run',
    tag: 'workflows',
    scope: 'workflows:write',
  }),
  r({
    method: 'POST',
    path: '/v1/workflow-runs/:id/steps/:stepId/retry',
    summary: 'Retry a failed step',
    tag: 'workflows',
    scope: 'workflows:write',
  }),
  r({
    method: 'POST',
    path: '/hooks/:workflowId/:secret',
    summary: 'Webhook trigger (JSON Schema validated)',
    tag: 'workflows',
    auth: 'public',
  }),
  r({
    method: 'POST',
    path: '/dev/echo',
    summary: 'Development echo endpoint (records requests)',
    tag: 'system',
    auth: 'public',
  }),
  r({
    method: 'GET',
    path: '/dev/echo',
    summary: 'Requests received by the echo endpoint',
    tag: 'system',
    auth: 'public',
  }),
];
